name: Detect missing mlibc-config.h

on: [pull_request, merge_group]

jobs:
  find-misuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x ./scripts/check-options-header-include.sh && ./scripts/check-options-header-include.sh
